export enum Role {
  SUPER_ADMINISTRATOR = 'SUPER_ADMINISTRATOR',
  ADMINISTRATOR = 'ADMINISTRATOR',
  ONCOLOGIST = 'ONCOLOGIST',
  RADIONCOLOGIST = 'RADIONCOLOGIST',
  NURSE = 'NURSE',
  RADIOTHERAPIST = 'RADIOTHERAPIST',
}
